server:
  port: 80

#spring:
#  application:
#    name: cloud-order-service

eureka:
  client:
    register-with-eureka: false # 不注册进eureka服务中心
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/


#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下, 两端连接所用的时间
  ConnectTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 5000
feign:
#  httpclient:
#    ok-http:
#      read-timeout: 5
#    connection-timeout: 5000
  hystrix:
    enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。

logging:
  level:
    # feign日志以 debug 级别监控 com.atguigu.springcloud.service.PaymentFeignService 接口
    com.zys.springcloud.service.PaymentFeignService: debug

#feign:
#  hystrix:
#    enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。